# -*- coding: utf-8 -*-
# **************************************************************************
# *
# * Authors: Emmanuel Moebel (emmanuel.moebel@inria.fr)
# *
# * Inria - Centre de Rennes Bretagne Atlantique, France
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'you@yourinstitution.email'
# *
# **************************************************************************
from enum import Enum
from pyworkflow.object import String
from pyworkflow.protocol import params, PointerParam, STEPS_PARALLEL
from pyworkflow.utils import removeBaseExt, cyanStr
from pyworkflow.utils.properties import Message
from tomo.constants import BOTTOM_LEFT_CORNER
from tomo.objects import Coordinate3D, SetOfTomograms, SetOfCoordinates3D
from tomo.protocols import ProtTomoPicking
from deepfinder import Plugin
from deepfinder.constants import *
import deepfinder.convert as cv
from deepfinder.protocols import ProtDeepFinderBase
import os
from tomo.utils import getObjFromRelation
import logging
logger = logging.getLogger(__name__)


class DFClusterOutputs(Enum):
    coordinates = SetOfCoordinates3D


class DeepFinderCluster(ProtTomoPicking, ProtDeepFinderBase):
    """
    Analyses segmentation maps produced from tomographic data and
identifies discrete biological objects by converting segmented regions
into localized particle coordinates and class assignments. The protocol
is intended to transform voxel-based semantic segmentation information
into object-centered representations suitable for downstream structural
and biological interpretation.

    AI Generated:

    DeepFinder Cluster (DeepFinderCluster) — User Manual
        Overview

        The DeepFinder Cluster protocol is designed to detect and
separate individual biological objects from segmentation maps generated
during tomographic analysis. Its primary purpose is to identify distinct
particles, complexes, or cellular features inside segmented tomograms
and convert them into structured coordinate sets that can be used in
later stages of cryo-electron tomography workflows.

        In practical biological studies, segmentation maps often contain
dense regions corresponding to proteins, macromolecular assemblies,
viral particles, membranes, or organelles. While segmentation defines
which voxels belong to biologically meaningful structures, many
downstream analyses require discrete object positions rather than
continuous segmented regions. This protocol bridges that gap by locating
individual objects and assigning them to specific biological classes.

        Inputs and Biological Context

        The protocol requires segmentation maps as input. These maps are
typically generated by deep learning models trained to recognize
different structural categories within tomograms. Each segmented region
represents a predicted biological identity, allowing the protocol to
separate multiple classes of structures within the same cellular volume.

        From a biological perspective, the quality of the segmentation
strongly influences the quality of clustering results. Accurate
segmentation maps generally produce reliable object localization, whereas
oversegmented or noisy maps may lead to merged detections, false
positives, or fragmented biological structures.

        Clustering Radius and Object Separation

        One of the key parameters is the clustering radius, which defines
the approximate spatial scale used to separate neighboring objects. This
parameter should reflect the expected size of the biological structures
being analyzed.

        Small clustering radii are appropriate for compact particles such
as ribosomes or small protein complexes. Larger radii may be required
for extended assemblies, viral capsids, or large macromolecular
machines. Choosing an excessively small radius can artificially split a
single biological structure into multiple detections, whereas a radius
that is too large may merge nearby particles into a single object.

        Biological interpretation therefore depends strongly on selecting
a clustering scale consistent with the physical dimensions of the target
structures.

        Coordinate Generation and Classification

        The protocol produces three-dimensional coordinates associated
with detected objects. Each coordinate corresponds to the estimated
location of an individual biological entity inside the tomogram. In
addition to positional information, each object retains its predicted
class identity, enabling simultaneous analysis of multiple biological
species within the same dataset.

        Confidence values associated with detected objects may also help
users distinguish highly reliable detections from more uncertain
predictions. This can be particularly important in crowded cellular
environments where segmentation ambiguity is common.

        Outputs and Their Interpretation

        The resulting coordinate sets can be directly reused in many
cryo-electron tomography workflows, including subtomogram extraction,
subtomogram averaging, spatial statistics, visualization, and particle
classification. Because coordinates remain linked to their original
tomograms, biological context is preserved throughout downstream
processing.

        The protocol also generates a summary describing the number of
detected objects and their distribution across classes. This information
can provide a rapid overview of sample composition, particle abundance,
or segmentation quality.

        Typical Biological Applications

        Common applications include automated ribosome localization,
viral particle detection, membrane protein identification, cytoskeletal
mapping, and large-scale annotation of crowded cellular tomograms. The
protocol is especially valuable in studies where manual particle picking
would be impractical because of dataset size or structural complexity.

        In structural biology workflows, the generated coordinates often
serve as the starting point for subtomogram averaging pipelines. In cell
biology studies, they may support analyses of intracellular organization
or spatial relationships between molecular assemblies.

        Practical Recommendations

        Successful clustering depends heavily on segmentation quality and
appropriate parameter selection. Users are encouraged to visually inspect
segmentation maps before clustering to ensure that biologically relevant
structures are well separated and consistently labeled.

        The clustering radius should be selected according to the
expected dimensions of the target structures in voxels. When uncertain,
testing several values and visually validating the resulting coordinates
can substantially improve reliability.

        It is also advisable to inspect detected coordinates directly
within tomographic visualization tools to confirm that object centers are
correctly localized and biologically meaningful.

        Final Perspective

        Converting segmentation maps into discrete object coordinates is
a critical step in many automated cryo-electron tomography workflows. By
transforming dense voxel annotations into biologically interpretable
particle locations, the DeepFinder Cluster protocol enables efficient
integration of deep learning based segmentation with structural analysis,
subtomogram averaging, and quantitative cellular studies.
    """

    _label = 'cluster'
    _possibleOutputs = DFClusterOutputs
    stepsExecutionMode = STEPS_PARALLEL

    def __init__(self, **args):
        super().__init__(**args)
        self.clusteringSummary = String()
        self.tomoMasksDict = None

    # --------------------------- DEFINE param functions ----------------------
    def _defineParams(self, form):
        form.addSection(label=Message.LABEL_INPUT)

        form.addParam('inputSegmentations', PointerParam,
                      pointerClass='SetOfTomoMasks',
                      label="Segmentation maps",
                      important=True,
                      help='Please select the segmentation maps you would like to analyze.')
        form.addParam('cradius', params.IntParam,
                      default=5,
                      label='Clustering radius',
                      important=True,
                      help='Should correspond to average radius of target objects (in voxels)')
        form.addParallelSection(threads=4, mpi=1)

    # --------------------------- INSERT steps functions ----------------------
    def _insertAllSteps(self):
        self.__initialize()
        closeDeps = []
        ind = 0
        for tsId in self.tomoMasksDict.keys():
            pid = self._insertFunctionStep(self.launchClusteringStep, tsId,
                                           prerequisites=[],
                                           needsGPU=False)
            cOutId = self._insertFunctionStep(self.createOutputStep, tsId, ind,
                                           prerequisites=pid,
                                           needsGPU=False)
            closeDeps.append(cOutId)
            ind += 1
        self._insertFunctionStep(self._closeOutputSet,
                                 prerequisites=closeDeps,
                                 needsGPU=False)

    # --------------------------- STEPS functions -----------------------------
    def __initialize(self):
        self.tomoMasksDict = {tomoMask.getTsId(): tomoMask.clone() for tomoMask in self.inputSegmentations.get()}

    def launchClusteringStep(self, tsId: str):
        logger.info(cyanStr(f'Clustering step of ---> {tsId}'))
        segm = self.tomoMasksDict[tsId]
        fname_objl = 'objl_' + removeBaseExt(segm.getFileName()) + '.xml'
        fname_objl = os.path.abspath(os.path.join(self._getExtraPath(), fname_objl))

        # Launch DeepFinder executable:
        deepfinder_args = '-l ' + segm.getFileName()
        deepfinder_args += ' -r ' + str(self.cradius.get())
        deepfinder_args += ' -o ' + fname_objl

        Plugin.runDeepFinder(self, 'cluster', deepfinder_args)

    def createOutputStep(self, tsId: str, segmInd: int):
        with self._lock:
            segm = self.tomoMasksDict[tsId]
            logger.info(cyanStr(f'Generating the output of ---> {tsId}'))
            # Convert DeepFinder annotation output to Scipion SetOfCoordinates3D
            outCoords = self.createOutputSet()
            clusteringSummary = ''
            # Get objl filename:
            fname_segm = os.path.splitext(segm.getFileName())
            fname_segm = os.path.basename(fname_segm[0])
            fname_objl = 'objl_' + fname_segm + '.xml'

            # Read objl:
            objl_tomo = cv.objl_read(os.path.abspath(os.path.join(self._getExtraPath(), fname_objl)))

            # Generate string for protocol summary:
            msg = 'Segmentation ' + str(segmInd + 1) + ': a total of ' + str(
                len(objl_tomo)) + ' objects has been found.'
            clusteringSummary += msg
            lbl_list = cv.objl_get_labels(objl_tomo)
            for lbl in lbl_list:
                objl_class = cv.objl_get_class(objl_tomo, lbl)
                msg = '\nClass ' + str(lbl) + ': ' + str(len(objl_class)) + ' objects'
                clusteringSummary += msg
            clusteringSummary += '\n'

            # Get tomo corresponding to current tomomask:
            tomo = segm.getTomogram()
            tomoId = segm.getTsId()

            for idx in range(len(objl_tomo)):
                x = objl_tomo[idx][DF_COORD_X]
                y = objl_tomo[idx][DF_COORD_Y]
                z = objl_tomo[idx][DF_COORD_Z]
                lbl = objl_tomo[idx][DF_LABEL]
                score = objl_tomo[idx][DF_SCORE]

                coord = Coordinate3D()
                coord.setVolume(tomo)
                coord.setPosition(x, y, z, BOTTOM_LEFT_CORNER)
                coord.setTomoId(tomoId)
                coord.setVolId(segmInd + 1)
                coord.setGroupId(lbl)
                coord.setScore(score)

                outCoords.append(coord)

            self.clusteringSummary.set(clusteringSummary)
            self._store(self.clusteringSummary)

    # --------------------------- DEFINE info functions ---------------------- # TODO
    def _summary(self):
        """ Summarize what the protocol has done"""
        summary = []
        if self.isFinished():
            if self.clusteringSummary.get():
                summary.append(self.clusteringSummary.get())

            # if self._noAnnotations.get():
            #     summary.append('NO OBJECTS WERE TAKEN.')

        return summary

    # --------------------------- UTILS functions -----------------------------
    def createOutputSet(self) -> SetOfCoordinates3D:
        outCoords = getattr(self, self._possibleOutputs.coordinates.name, None)
        boxSize = 2 * self.cradius.get()
        if outCoords:
            outCoords.enableAppend()
        else:
            setSegmentations = self.inputSegmentations.get()
            tomograms = getObjFromRelation(setSegmentations, self, SetOfTomograms)
            outCoords = SetOfCoordinates3D.create(self.getPath(), template='coordinates%s.sqlite')
            outCoords.setName('Detected objects')
            outCoords.setPrecedents(tomograms)
            outCoords.setSamplingRate(setSegmentations.getSamplingRate())
            outCoords.setBoxSize(boxSize)
            outCoords.setStreamState(outCoords.STREAM_OPEN)

            # Define relations
            self._defineOutputs(**{self._possibleOutputs.coordinates.name: outCoords})
            self._defineSourceRelation(self.inputSegmentations, outCoords)

        return outCoords
