# -*- coding: utf-8 -*-
# **************************************************************************
# *
# * Authors: Emmanuel Moebel (emmanuel.moebel@inria.fr)
# *
# * Inria - Centre de Rennes Bretagne Atlantique, France
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'you@yourinstitution.email'
# *
# **************************************************************************
import os
from enum import Enum
from os.path import basename

from deepfinder.constants import *
from pyworkflow.protocol import LEVEL_ADVANCED
from pyworkflow.utils import removeBaseExt
from tomo.constants import BOTTOM_LEFT_CORNER
from tomo.objects import SetOfCoordinates3D, Coordinate3D
from tomo.protocols.protocol_base import ProtTomoImportFiles
import pyworkflow.protocol.params as params
import deepfinder.convert as cv


class DFImportCoordsOutputs(Enum):
    coordinates = SetOfCoordinates3D


class ImportCoordinates3D(ProtTomoImportFiles):
    """
    Imports DeepFinder object annotations and converts them into a
standardized set of 3D coordinates associated with tomograms. The
protocol enables the integration of DeepFinder detection results into
tomographic workflows where coordinates are required for visualization,
particle extraction, subtomogram averaging, or downstream structural
analysis.

    AI Generated:

    Import DeepFinder Coordinates (ImportCoordinates3D) — User Manual
        Overview

        The Import DeepFinder Coordinates protocol is designed to bring
object detection results generated by DeepFinder into a tomographic data
management environment as structured 3D coordinates. Its primary goal is
to transform externally generated particle or object annotations into a
format that can be directly reused in cryo-electron tomography workflows.

        In practical biological research, this protocol is commonly used
after automated particle detection or semantic segmentation procedures.
Once DeepFinder has identified candidate macromolecules, cellular
components, or structural features inside tomograms, the resulting object
lists can be imported as coordinate sets for further analysis. This
allows users to continue processing within a unified framework without
manually recreating annotations.

        Inputs and Coordinate Association

        The protocol requires a set of tomograms together with coordinate
files generated externally. Each coordinate file is expected to
correspond to a specific tomogram, and successful association depends on
consistent naming between tomograms and annotation files. Maintaining a
clear naming convention is therefore essential for reliable import.

        Biologically, this mapping step is important because coordinates
must remain associated with the correct cellular context. Incorrect file
matching could lead to particle locations being assigned to the wrong
sample, producing invalid downstream interpretations.

        Coordinate Interpretation

        Imported coordinates represent spatial locations of detected
objects inside three-dimensional tomograms. These objects may correspond
to protein complexes, ribosomes, viral particles, membrane-associated
assemblies, cytoskeletal elements, or any other biological feature that
DeepFinder was trained to recognize.

        Each coordinate may also contain additional information such as
class identity or confidence estimation. The class assignment allows
multiple biological structures to coexist within the same tomogram while
remaining distinguishable during later analyses. Confidence values can
help users prioritize detections for validation, subtomogram averaging,
or manual inspection.

        Box Size and Downstream Processing

        The protocol allows the definition of a box size associated with
the imported coordinates. This parameter is biologically relevant because
it defines the approximate spatial region surrounding each detected
particle that may later be extracted for subtomogram analysis or particle
refinement.

        Choosing an appropriate box size depends on the expected size of
the biological structure. Small particles generally require compact boxes
to reduce background noise, whereas large macromolecular assemblies or
membrane-associated complexes may require substantially larger regions to
fully capture structural context.

        Coordinate Systems and Spatial Consistency

        Spatial consistency is essential in cryo-electron tomography. The
imported coordinates preserve positional information relative to the
original tomograms, ensuring compatibility with visualization tools,
particle extraction utilities, and structural refinement pipelines.

        From a biological perspective, maintaining accurate spatial
relationships is critical when studying intracellular organization,
macromolecular crowding, or interactions between complexes. Even small
coordinate inconsistencies may affect particle centering and reduce the
quality of downstream reconstructions.

        Typical Biological Applications

        This protocol is especially useful in workflows involving
automated particle detection in crowded cellular environments. Common
applications include ribosome localization, viral particle detection,
membrane protein identification, organelle mapping, and large-scale
annotation of tomographic datasets.

        In subtomogram averaging workflows, imported coordinates often
serve as the starting point for particle extraction and alignment. In
cellular structural biology, they may also be used for spatial statistics
or for studying the organization of complexes within native cellular
environments.

        Practical Recommendations

        Before importing coordinates, users should verify that tomogram
names and coordinate file names match exactly. Consistent voxel sizes and
proper tomogram orientation are also important to avoid positional
mismatches.

        It is advisable to visually inspect a subset of imported
coordinates after import. This validation step helps confirm that
detections are correctly positioned within the biological structures of
interest and that no coordinate inversion or scaling issues are present.

        When importing coordinates originating from multiple classes,
users should ensure that the biological meaning of each class is clearly
understood and consistently interpreted throughout downstream analyses.

        Final Perspective

        For many cryo-electron tomography studies, automated detection is
only the beginning of the analysis pipeline. The ability to reliably
import DeepFinder coordinates into a structured tomographic workflow
provides a bridge between machine learning based detection and biological
interpretation. Accurate coordinate handling ultimately enables more
robust particle extraction, visualization, structural averaging, and
quantitative spatial analysis in complex biological specimens.
    """

    _label = 'import DeepFinder coordinates'
    _possibleOutputs = DFImportCoordsOutputs

    def _defineParams(self, form):
        ProtTomoImportFiles._defineImportParams(self, form)

        form.addParam('importTomograms', params.PointerParam,
                      pointerClass='SetOfTomograms',
                      label='Input tomograms',
                      help='Select the tomograms/tomogram for which you '
                           'want to import coordinates. The file names of the tomogram and '
                           'coordinate files must be the same.')
        form.addParam('boxSize', params.IntParam,
                      label="Box size",
                      expertLevel=LEVEL_ADVANCED,
                      default=50,
                      help='Default box size for the output.')

    def _insertAllSteps(self):
        self._insertFunctionStep(self.importCoordinatesStep)

    # --------------------------- STEPS functions -----------------------------
    def importCoordinatesStep(self):
        importTomograms = self.importTomograms.get()
        boxSize = self.boxSize.get()
        coord3DSet = SetOfCoordinates3D.create(self._getPath(), template='coordinates.sqlite')
        coord3DSet.setPrecedents(importTomograms)
        coord3DSet.setBoxSize(boxSize)
        coord3DSet.setSamplingRate(importTomograms.getSamplingRate())
        coordCounter = 1
        for tomoInd, tomo in enumerate(importTomograms.iterItems()):
            tomoName = basename(os.path.splitext(tomo.getFileName())[0])
            for coordFile, fileId in self.iterFiles():
                fileName = removeBaseExt(coordFile)

                if tomo is not None and tomoName == fileName:
                    objl = cv.objl_read(coordFile)

                    for idx in range(len(objl)):
                        iobjl = objl[idx]
                        x = iobjl[DF_COORD_X]
                        y = iobjl[DF_COORD_Y]
                        z = iobjl[DF_COORD_Z]
                        lbl = iobjl[DF_LABEL]
                        score = iobjl.get(DF_SCORE, None)

                        coord = Coordinate3D()
                        coord.setVolume(tomo)
                        coord.setObjId(coordCounter)
                        coord.setPosition(x, y, z, BOTTOM_LEFT_CORNER)
                        coord.setVolId(tomoInd + 1)
                        coord.setBoxSize(boxSize)
                        coord.setGroupId(lbl)
                        coord.setScore(score)

                        coord3DSet.append(coord)
                        coordCounter += 1

        self._defineOutputs(**{self._possibleOutputs.coordinates.name: coord3DSet})
        self._defineSourceRelation(self.importTomograms, coord3DSet)
